### ISSUE TITLE
Time span of the articles

### ISSUE THREAD

**Issue by severinsimmler** [tblock/10kGNAD#3]
Thanks a lot for sharing your dataset!

What is the time span of the articles, i.e. from when is the oldest and from when the newest? Years would be enough for me.

**Comment by tblock** [comment]
The dataset is based on the [One Million Post Corpus](https://ofai.github.io/million-post-corpus/). They provide a SQLite database with the articles.
```
sqlite> SELECT min(publishingDate), max(publishingDate) FROM Articles;
2002-07-06 12:19:00.00|2016-05-31 18:08:20.00
``` 
So a rough answer would be from 2002 to 2016. However this might be not 100% accurate, since the 10kGNAD does not use all articles (~85%) from the One Million Post Corpus.

**Comment by severinsimmler** [comment]
Thanks for this quick response!
